name: coordonate_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  build_runner: ^2.4.5
  cupertino_icons: ^1.0.2
  cupertino_onboarding: ^1.1.1
  dartz: ^0.10.1
  dio: ^5.2.1
  fancy_password_field: ^2.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_dotenv: ^5.0.2
  flutter_screenutil: ^5.8.4
  flutter_svg: ^0.22.0
  freezed: ^2.3.5
  freezed_annotation: ^2.2.0
  get_it: ^7.6.0
  intl_phone_field: ^3.1.0
  loading_animation_widget: ^1.2.0+4
  logger: ^1.4.0
  pin_code_fields: ^8.0.1
  pinput: ^2.2.31
  shared_preferences: ^2.1.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  husky: ^0.1.6
  test: ^1.22.0

flutter:
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Light.ttf
          weight: 100
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 400
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 600
  uses-material-design: true

  assets:
    - assets/images/auth/
    - assets/images/auth/onboarding/

  #   - .env
  #   - .env.development
  #   - .env.production
